name: Build Training Image

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    uses: MLops-Project-Platform/mlops-platform/.github/workflows/build-training-image.yaml@main
    with:
      image_name: mlops-research-template
      dockerfile_path: training-runtime/Dockerfile
    secrets:
      GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
